### ISSUE TITLE
FROST: The Production Impact and Why It Matters

### ISSUE THREAD

**Issue by 0xcoolgirl** [TABConf/6.tabconf.com#50] opened 2024-07-08 14:59 UTC
Armin Sabouri, CTO, Botanix Labs - PANEL
Other Guests: Nick Farrow, Jesse Posner, Chelsea Komlo
Moderator (Suggestion): Satsie

# Description
### What is this panel discussion about? Please give us as many details as possible. 
Requirements for Bitcoin key management are ever more demanding, and many off-chain tools require user dependence on hot keys instead of (safer) cold keys. Breakthroughs in cryptography like Flexible Round-Optimized Schnorr Threshold Signatures (FROST) and the Taproot upgrade are helping developers and users re-think their approaches to private key security. FROST is a protocol that minimizes the number of rounds of communication between participants in Schnorr signature schemes to reduce network bandwidth, time, and probability of errors. Cryptographers, protocol developers, and other Bitcoin builders will discuss the state of FROST, its use by Bitcoin companies, and its potential for reshaping Bitcoin security. 

### What would an attendee learn from this talk?
The Basics: “What is F.R.O.S.T.?”
Comparing offchain and onchain multisig tools 
Comparing different multisig key aggregation schemes
Overview of FROST, Frostsnap, and other private collaborative custody tools

### Is there anything folks should read up on before they attend this talk?
https://en.bitcoin.it/wiki/BIP_0340 
https://gist.github.com/nickfarrow/4be776782bce0c12cca523cbc203fb9d/?ref=tftc.io 
https://frostsnap.com/introducing-frostsnap.html 
https://www.tftc.io/issue-1379-using-frost-to-increase-privacy-in-collaborative-bitcoin-custody-models/ 
https://brink.dev/blog/2021/04/15/frost/ 

### Relevant Links

# About the panelist
### Social Links
GitHub: github.com/0xBEEFCAF3
Twitter: @Arminsdev
Website: www.botanixlabs.xyz

# Panel Discussion Details
### Preferred Day/Time Slot: October 24, midday 
*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by iglesiasbrandon** [comment] 2024-07-24 14:54
hey @0xcoolgirl, thank you for submitting this issue; we dont have panels and talks on the 23rd or the 24th. between the 25th and 26th, what day would you prefer?

**Comment by satsie** [comment] 2024-07-28 17:29
I haven't spoken with @0xcoolgirl personally but I would love to take up the suggestion to moderate this panel if the opportunity is available! My preference is for the 25th.

**Comment by 0xcoolgirl** [comment] 2024-07-29 01:56
Hi Brandon and Stacie - thanks! We'd love to have Stacie moderate 💪

Brandon, I'm confirming with Armin and Willem which dates work best for
them and will get back to you asap.

And Brandon, quick question. Will TABConference be working to finalize
other panelists for both panels? How does that work?

**Comment by 0xBEEFCAF3** [comment] 2024-07-31 15:10
25th works for me!

**Comment by iglesiasbrandon** [comment] 2024-07-31 20:24
@0xcoolgirl its byop (bring your own panelist!) If you and @satsie want to collaborate and reach out to the folks you suggested and confirm them then that works! just update the issue description when the panelist have been confirmed. This is an example from last year: https://github.com/TABConf/2023.tabconf.com/issues/52

Please have the panelist confirm by adding an 'ack' on this issue so that we can also assign them to the issue!

**Comment by 0xcoolgirl** [comment] 2024-07-31 20:47
Hey Brandon, thank you for this!

We weren't under the impression it would be our responsibility to find
other panelists. We're focused largely on scaling our business and
preparing for mainnet. That said, we don't have the resources to support on
the panelist curation front.

**Comment by satsie** [comment] 2024-08-01 00:03
I might be able to bring this to the attention of a few of the unconfirmed panelists. Stand by please 🫡

**Comment by jesseposner** [comment] 2024-08-01 03:39
ack

**Comment by satsie** [comment] 2024-08-02 19:33
I've spoken with Nick Farrow and it's unlikely he's going to be able to attend TABConf this year. In light of this, I'd like to nominate Jurvis Tan (https://github.com/jurvis), an engineer at Block to be a panelist. He's very knowledgeable and enthusiastic about FROST and I think would be an awesome addition! Any objections if we add him?

**Comment by iglesiasbrandon** [comment] 2024-08-03 12:04
Hey @satsie that sounds awesome; can you reach out to @jurvis and ask them to ack this issue if they agree to be a panelist?!

**Comment by jurvis** [comment] 2024-08-03 13:02
ack!

**Comment by satsie** [comment] 2024-09-03 17:45
Hi TABConf team! Are you able to confirm if this panel can happen on the 25th? I know the initial issue description says 10/24 but I think that's a workshop and builder day. I will not be around on the 26th so hoping this can definitely be scheduled for the 24th :)

Chelsea Komlo has a prior engagement and will not be able to attend. She has nominated a colleague to fill her spot that I am following up with. If not, there are a few others I'd like to check with about possibly joining the panel.

**Comment by iglesiasbrandon** [comment] 2024-09-03 22:02
Hey @satsie, yeah, we can slot this in for the 25th!

**Comment by iglesiasbrandon** [comment] 2024-09-03 22:04
Hey @satsie,

Would you say this is beginner, intermediate or advance panel?

We are collecting an additional attribute for each issue. Let me know what difficulty level we should assign to this. 

- Beginner: would be no prior knowledge needed, very few technical skills required for workshop
- Intermediate: At least some knowledge needed to not be lost, technical skills, Comp Sci, IT related experience is greatly beneficial
- Advanced: Potentially a strong working knowledge of certain technologies, libraries, fundamentals, Comp Sci, and related protocols.

Error on the side of more advanced than less advanced as we want to set expectations with attendees!

**Comment by satsie** [comment] 2024-09-04 17:18
Thanks so much @iglesiasbrandon! Let's mark this as intermediate.

**Comment by jurvis** [comment] 2024-09-05 16:50
@iglesiasbrandon do we know generally what time this panel would be? is it possible to request for an 11-ish timeslot?

**Comment by jesseposner** [comment] 2024-09-05 16:58
The author of the FROST signing [BIP](https://github.com/siv2r/bip-frost-signing), @siv2r, might be attending TABConf. If he's able to make it, he'd make a great addition to the panel.

**Comment by siv2r** [comment] 2024-09-06 13:28
Thank you, @jesseposner, for the recommendation! I’d be glad to join this panel. I’m in the process of obtaining my US visa and will send an ack here if it’s approved!

**Comment by conradoplg** [comment] 2024-09-06 15:08
Sorry for not replying on Twitter @satsie, it's blocked here now

Unfortunately I can't make it :frowning_face:  but thanks for the invite.

**Comment by satsie** [comment] 2024-10-02 03:37
We're sad you won't be able to join us but thank you so much for popping in here @conradoplg and letting us know! 

@siv2r you don't by any chance have an update do you? Would love if you could make it!

**Comment by siv2r** [comment] 2024-10-02 06:23
@satsie, I really wanted to be there, but my US visa was denied (two times!), so I won’t be able to attend.

**Comment by satsie** [comment] 2024-10-02 18:57
@siv2r I am so sorry to hear this :( Thanks for the update, even if it is not the outcome we hoped

**Comment by satsie** [comment] 2024-10-16 11:05
@jonasnick is going to be our 4th panelist 🎉 I will ask him to please ACK this issue

**Comment by jonasnick** [comment] 2024-10-16 21:28
ACK :rocket:

**Comment by iglesiasbrandon** [comment] 2024-10-25 18:37
thank you for conducting this panel!

**Closed by iglesiasbrandon** 2024-10-25 18:37 UTC
Labels: Accepted, Panel
